<?php

namespace Tests\Feature;

use App\Models\Todo;
use Database\Seeders\TodoSeeder;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Foundation\Testing\WithFaker;
use Illuminate\Support\Facades\DB;
use Tests\TestCase;

class TodoControllerTest extends TestCase
{
    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        DB::delete('DELETE FROM todos');
    }

    public function test_todo_page()
    {
        $this->seed(TodoSeeder::class);

        $this->withSession([
            'user' => 'test@localhost'
        ])->get('/todos')
            ->assertSeeText('Learning Laravel')
            ->assertSeeText('Learning Vue');
    }

    public function test_add_todo_failed()
    {
        $this->withSession([
            'user' => 'test@localhost'
        ])->post('/todos', [])
            ->assertSeeText('Todo is required');
    }

    public function test_add_todo_success()
    {
        $this->withSession([
            'user' => 'test@localhost'
        ])->post('/todos', [
            'todo' => 'Sleep'
        ])->assertRedirect('/todos');
    }

    public function test_remove_todo()
    {
        $this->seed(TodoSeeder::class);
        $todos = Todo::query()->get();
        
        $this->withSession([
            'user' => 'test@localhost'
        ])->post('/todos/' . $todos[0]->id )
            ->assertRedirect('/todos');
    }
}
