<?php

namespace Tests\Feature;

use Database\Seeders\UserSeeder;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Foundation\Testing\WithFaker;
use Illuminate\Support\Facades\DB;
use Tests\TestCase;

class UserControllerTest extends TestCase
{
    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->withoutExceptionHandling();
        DB::delete("delete from users");
    }

    public function test_login_page()
    {
        $this->get('/login')
            ->assertSeeText("Login");
    }

    public function test_login_page_for_member()
    {
        $this->withSession([
            "user" => "test@localhost"
        ])->get('/login')
            ->assertRedirect("/");
    }

    public function test_login_success()
    {
        $this->seed(UserSeeder::class);

        $this->post('/login', [
            "user" => "test@localhost",
            "password" => "test"
        ])->assertRedirect("/")
            ->assertSessionHas("user", "test@localhost");
    }

    public function test_login_for_user_already_login()
    {
        $this->withSession([
            "user" => "test@localhost"
        ])->post('/login', [
            "user" => "test@localhost",
            "password" => "test"
        ])->assertRedirect("/");
    }

    public function test_login_validation_error()
    {
        $this->post("/login", [])
            ->assertSeeText("Email or Password is required");
    }

    public function test_login_failed()
    {
        $this->post('/login', [
            'user' => "wrong",
            "password" => "wrong"
        ])->assertSeeText("Email or Password is wrong");
    }

    public function test_logout()
    {
        $this->withSession([
            "user" => "test@localhost"
        ])->post('/logout')
            ->assertRedirect("/")
            ->assertSessionMissing("user");
    }

    public function test_logout_guest()
    {
        $this->post('/logout')
            ->assertRedirect("/");
    }
}
